org.gradle.jvmargs=-Xmx2g -Xss512k -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:MaxMetaspaceSize=512m -XX:CICompilerCount=2
org.gradle.workers.max=1
kotlin.daemon.jvmargs=-Xmx1g
kotlin.code.style=official
android.useAndroidX=true
android.debug.obsoleteApi=true
android.nonTransitiveRClass=true
android.builder.sdkDownload=true
